[platformio]
default_envs = pico

[env]
framework = arduino
monitor_speed = 115200
build_flags = -D PD_TRAINER_PPM_PIN=2

[env:pico]
platform = raspberrypi
board = pico

[env:teensy40]
platform = teensy
board = teensy40
